package dev.mvc.calendar;

import java.time.LocalDateTime;
import java.util.Date;

import lombok.Getter;
import lombok.Setter;

//CREATE TABLE calendar_log (
//    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    calendarno   NUMBER NOT NULL,
//    action       VARCHAR2(20) NOT NULL, -- 수정, 삭제
//    memberno     NUMBER NOT NULL,        -- 수정/삭제 한 사람
//    action_date  DATE DEFAULT SYSDATE,
//    old_title    VARCHAR2(100),
//    old_content  CLOB,
//    FOREIGN KEY (calendarno) REFERENCES calendar (calendarno),
//    FOREIGN KEY (memberno) REFERENCES member (memberno)
//  );

@Getter @Setter
public class CalendarLogVO {

  /** 로그 ID */
  private int log_id;

  /** 캘린더 번호 */
  private int calendarno;

  /** 동작 종류 (수정/삭제) */
  private String action;

  /** 작업한 회원 번호 */
  private int memberno;

  /** 작업 날짜 */
  private LocalDateTime action_date;

  /** 이전 제목 */
  private String old_title;

  /** 이전 내용 */
  private String old_content;
}