DROP TABLE calendar CASCADE CONSTRAINTS;
DROP TABLE calendar_log CASCADE CONSTRAINTS;
DROP TABLE calendar;
DROP TABLE calendar_log;

---- Oracle 12C+ (참고용)
--CREATE TABLE calendar (
--  calendarno  NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1), -- AUTO_INCREMENT 대체
--  labeldate   VARCHAR2(10)  NOT NULL, -- 출력할 날짜 2013-10-20
--  label       VARCHAR2(50)  NOT NULL, -- 달력에 출력될 레이블
--  title       VARCHAR2(100) NOT NULL, -- 제목(*)
--  content     CLOB          NOT NULL, -- 글 내용
--  cnt         NUMBER        DEFAULT 0, -- 조회수
--  seqno       NUMBER(5)     DEFAULT 1 NOT NULL, -- 일정 출력 순서
--  regdate     DATE          NOT NULL, -- 등록 날짜
--  PRIMARY KEY (calendarno)
--);

CREATE TABLE calendar (
  calendarno  NUMBER(10) NOT NULL,  -- PK
  labeldate   DATE NOT NULL,         -- 출력할 날짜
  startdate   DATE NOT NULL,         -- 시작일
  enddate     DATE NOT NULL,         -- 종료일
  label       VARCHAR2(50) NOT NULL, -- 달력에 출력될 레이블
  title       VARCHAR2(100) NOT NULL, -- 제목
  content     CLOB NOT NULL,          -- 내용
  cnt         NUMBER DEFAULT 0,       -- 조회수
  seqno       NUMBER(5) DEFAULT 1 NOT NULL, -- 순서
  regdate     DATE DEFAULT SYSDATE NOT NULL, -- 등록일
  memberno    NUMBER(10) NOT NULL,    -- FK
  PRIMARY KEY (calendarno),
  FOREIGN KEY (memberno) REFERENCES member (memberno)
);

-- 캘린더 수정/삭제 로그 테이블 (시퀀스 기반)
CREATE TABLE calendar_log (
  log_id       NUMBER(10) PRIMARY KEY,          -- 시퀀스 기반 PK
  calendarno   NUMBER(10) NOT NULL,             -- 캘린더 번호 FK
  action       VARCHAR2(20) NOT NULL,           -- '수정', '삭제'
  memberno     NUMBER(10) NOT NULL,             -- 작업자(수정/삭제 한 사람)
  action_date  DATE DEFAULT SYSDATE,            -- 작업일시
  old_title    VARCHAR2(100),                   -- 이전 제목
  old_content  CLOB,                            -- 이전 본문
  FOREIGN KEY (calendarno) REFERENCES calendar (calendarno),
  FOREIGN KEY (memberno) REFERENCES member (memberno)
);

DROP SEQUENCE calendar_seq;

CREATE SEQUENCE calendar_seq
START WITH 1         -- 시작 번호
INCREMENT BY 1       -- 증가값
MAXVALUE 9999999999  -- 최대값: 9999999999 --> NUMBER(10) 대응
CACHE 2              -- 2번은 메모리에서만 계산
NOCYCLE;             -- 다시 1부터 생성되는 것을 방지

DROP SEQUENCE calendar_log_seq;

CREATE SEQUENCE calendar_log_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;

-- 현재 락 걸린 세션 확인
SELECT
    l.session_id AS sid,
    s.serial#,
    s.username,
    l.locked_mode,
    o.object_name,
    o.object_type
FROM
    v$locked_object l,
    all_objects o,
    v$session s
WHERE
    l.object_id = o.object_id
    AND l.session_id = s.sid;

-- 락 걸린거 삭제
ALTER SYSTEM KILL SESSION '49,13859';

-- 컬럼 길이 증가
ALTER TABLE calendar MODIFY labeldate DATE;
ALTER TABLE calendar MODIFY startdate DATE;
ALTER TABLE calendar MODIFY enddate DATE;

-- 이미지
ALTER TABLE calendar ADD file1saved VARCHAR2(200);
ALTER TABLE calendar ADD file1origin VARCHAR2(200);
ALTER TABLE calendar ADD file1size NUMBER;

-- 카테고리 번호
ALTER TABLE calendar ADD cateno NUMBER(10);

-- FK 연결 (옵션)
ALTER TABLE calendar ADD CONSTRAINT calendar_fk_cate FOREIGN KEY (cateno) REFERENCES cate(cateno);

CREATE INDEX idx_calendar_dates ON calendar (startdate, enddate);

-- 공개 여부
ALTER TABLE calendar ADD visible CHAR(1) DEFAULT 'Y';

-- 여름 대축제 (기간 이벤트) → 카테고리: 행사 (cateno=1)
INSERT INTO calendar(calendarno, labeldate, startdate, enddate, label, title, content, cnt, seqno, regdate, memberno, cateno)
VALUES (calendar_seq.nextval, '2025-06-15', '2025-06-10', '2025-06-20', '여름 대축제', '여름 맞이 트리 10% 할인', '여름 대축제 기간입니다.', 0, 1, sysdate, 1, 1);

-- 여름 당일 이벤트 → 카테고리: 이벤트 (cateno=3)
INSERT INTO calendar(calendarno, labeldate, startdate, enddate, label, title, content, cnt, seqno, regdate, memberno, cateno)
VALUES (calendar_seq.nextval, '2025-06-18', '2025-06-18', '2025-06-18', '여름 할인', '여름 당일 특별 할인 20%', '오늘만 진행되는 여름 할인 이벤트입니다.', 0, 1, sysdate, 1, 3);

-- 재입고 안내 (하루짜리) → 카테고리: 공지 (cateno=2)
INSERT INTO calendar(calendarno, labeldate, startdate, enddate, label, title, content, cnt, seqno, regdate, memberno, cateno)
VALUES (calendar_seq.nextval, '2025-06-22', '2025-06-22', '2025-06-22', '재입고 안내', '참외 재입고', '오늘 참외가 재입고 됩니다.', 0, 2, sysdate, 1, 2);

-- 6월 마지막 전상품 세일 (1일 이벤트) → 카테고리: 이벤트 (cateno=3)
INSERT INTO calendar(calendarno, labeldate, startdate, enddate, label, title, content, cnt, seqno, regdate, memberno, cateno)
VALUES (calendar_seq.nextval, '2025-06-30', '2025-06-30', '2025-06-30', '6월 마지막 세일', '전상품 20% 할인', '6월 마지막 하루동안 진행되는 전상품 세일입니다.', 0, 2, sysdate, 1, 3);

COMMIT;

-- 전체 목록
SELECT calendarno, labeldate, startdate, enddate, label, title, content, cnt, seqno, regdate, memberno
FROM calendar
ORDER BY calendarno DESC;

-- 특정 달의 목록
SELECT calendarno, labeldate, label, seqno
FROM calendar
WHERE SUBSTR(labeldate, 1, 7) = '2024-12'
ORDER BY labeldate ASC, seqno ASC;

SELECT calendarno, labeldate, label, seqno
FROM calendar
WHERE TO_CHAR(TO_DATE(labeldate, 'YYYY-MM-DD'), 'YYYY-MM') = '2024-12'
ORDER BY labeldate ASC, seqno ASC;

CALENDARNO LABELDATE  LABEL                               SEQNO
---------- ---------- ------------------------------ ----------
         1 2024-12-24 크리스마스 이브                         1
         2 2024-12-25 휴강 안내                               1
         3 2024-12-25 학원 출입 안내                          2

-- 특정 날짜의 목록
SELECT calendarno, labeldate, label, seqno
FROM calendar
WHERE labeldate = '2024-12-24';

CALENDARNO LABELDATE  LABEL                                                   SEQNO
---------- ---------- -------------------------------------------------- ----------
         1 2024-12-24 크리스마스 이브                                             1

-- 조회수 증가
UPDATE calendar
SET cnt = cnt + 1
WHERE calendarno = 1;

-- 조회
SELECT calendarno, labeldate, label, title, content, cnt, regdate, seqno
FROM calendar
WHERE calendarno = 1;

-- 변경
UPDATE calendar
SET labeldate = '', label = '', title = '', content = '', seqno = 1
WHERE calendarno = 1;

-- 삭제
DELETE FROM calendar
WHERE calendarno = 1;

