-- ✅ 기존 Q&A 테이블이 없으니 새로 생성
DROP TABLE qna CASCADE CONSTRAINTS;
DROP TABLE qna_comment CASCADE CONSTRAINTS;

CREATE TABLE qna (
    qna_id       NUMBER(10)     NOT NULL,   -- Q&A 번호 (PK)
    title        VARCHAR2(200)  NOT NULL,   -- 제목
    content      CLOB           NOT NULL,   -- 내용
    user_type    VARCHAR2(20)   NOT NULL,   -- 사용자 유형 ('user' / 'supplier')
    writer_id    VARCHAR2(50)   NOT NULL,   -- 작성자 ID
    writer_name  VARCHAR2(50),              -- 작성자 이름
    reg_date     DATE           DEFAULT SYSDATE,  -- 등록일
    PRIMARY KEY (qna_id)
);

CREATE TABLE qna_comment (
  comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qna_id NUMBER NOT NULL,
  content VARCHAR2(4000),
  reg_date DATE DEFAULT SYSDATE,
  FOREIGN KEY (qna_id) REFERENCES qna(qna_id)
);

-- ✅ 시퀀스 생성
DROP SEQUENCE qna_seq;

CREATE SEQUENCE qna_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;

SELECT qna_id, cate FROM qna;

SELECT qna_id, title, reg_date, writer_name, comment_count, cate
FROM qna;

-- 댓글 수 저장하는 컬럼
ALTER TABLE qna ADD comment_count NUMBER DEFAULT 0;

ALTER TABLE qna ADD cate VARCHAR2(100);

ALTER TABLE qna ADD comment VARCHAR2(4000);

-- 소비자 Q&A
INSERT INTO qna (qna_id, title, content, user_type, writer_id, writer_name, cate)
VALUES (qna_seq.nextval, '배송 문의', '배송이 언제 되나요?', 'user', 'user1', '홍길동', '문의');

-- 공급자 Q&A
INSERT INTO qna (qna_id, title, content, user_type, writer_id, writer_name, cate)
VALUES (qna_seq.nextval, '상품 등록 문의', '상품 등록 방법이 궁금합니다.', 'supplier', 'supplier1', '이몽룡', '문의');

COMMIT;

-- 소비자용 Q&A
SELECT * FROM qna WHERE user_type = 'user';

-- 공급자용 Q&A
SELECT * FROM qna WHERE user_type = 'supplier';
